export type VanillaValueEffectTypes = (string & {})
    | "minecraft:set"
    | "minecraft:add"
    | "minecraft:multiply"
    | "minecraft:remove_binomial"
    | "minecraft:all_of"

export type VanillaEntityEffectTypes = (string & {})
    | "minecraft:all_of"
    | "minecraft:apply_impulse"
    | "minecraft:apply_exhaustion"
    | "minecraft:apply_mob_effect"
    | "minecraft:damage_entity"
    | "minecraft:change_item_damage"
    | "minecraft:explode"
    | "minecraft:ignite"
    | "minecraft:play_sound"
    | "minecraft:replace_block"
    | "minecraft:replace_disk"
    | "minecraft:run_function"
    | "minecraft:set_block_properties"
    | "minecraft:spawn_particles"
    | "minecraft:summon_entity";

export type VanillaEnchantments = (string & {})
    | "minecraft:aqua_affinity"
    | "minecraft:bane_of_arthropods"
    | "minecraft:binding_curse"
    | "minecraft:blast_protection"
    | "minecraft:breach"
    | "minecraft:channeling"
    | "minecraft:density"
    | "minecraft:depth_strider"
    | "minecraft:efficiency"
    | "minecraft:feather_falling"
    | "minecraft:fire_aspect"
    | "minecraft:fire_protection"
    | "minecraft:flame"
    | "minecraft:fortune"
    | "minecraft:frost_walker"
    | "minecraft:impaling"
    | "minecraft:infinity"
    | "minecraft:knockback"
    | "minecraft:looting"
    | "minecraft:loyalty"
    | "minecraft:luck_of_the_sea"
    | "minecraft:lunge"
    | "minecraft:lure"
    | "minecraft:mending"
    | "minecraft:multishot"
    | "minecraft:piercing"
    | "minecraft:power"
    | "minecraft:projectile_protection"
    | "minecraft:protection"
    | "minecraft:punch"
    | "minecraft:quick_charge"
    | "minecraft:respiration"
    | "minecraft:riptide"
    | "minecraft:sharpness"
    | "minecraft:silk_touch"
    | "minecraft:smite"
    | "minecraft:soul_speed"
    | "minecraft:sweeping_edge"
    | "minecraft:swift_sneak"
    | "minecraft:thorns"
    | "minecraft:unbreaking"
    | "minecraft:vanishing_curse"
    | "minecraft:wind_burst";

export type VanillaLevelBasedValueTypes = (string & {})
    | "minecraft:exponent"
    | "minecraft:linear"
    | "minecraft:levels_squared"
    | "minecraft:clamped"
    | "minecraft:fraction"
    | "minecraft:lookup";

export type VanillaEnchantmentTags = (string & {})
    | "#minecraft:curse"
    | "#minecraft:double_trade_price"
    | "#minecraft:in_enchanting_table"
    | "#minecraft:non_treasure"
    | "#minecraft:on_mob_spawn_equipment"
    | "#minecraft:on_random_loot"
    | "#minecraft:on_traded_equipment"
    | "#minecraft:prevents_bee_spawns_when_mining"
    | "#minecraft:prevents_decorated_pot_shattering"
    | "#minecraft:prevents_ice_melting"
    | "#minecraft:prevents_infested_spawns"
    | "#minecraft:smelts_loot"
    | "#minecraft:tooltip_order"
    | "#minecraft:tradeable"
    | "#minecraft:treasure"
    | "#minecraft:exclusive_set/armor"
    | "#minecraft:exclusive_set/boots"
    | "#minecraft:exclusive_set/bow"
    | "#minecraft:exclusive_set/crossbow"
    | "#minecraft:exclusive_set/damage"
    | "#minecraft:exclusive_set/mining"
    | "#minecraft:exclusive_set/riptide"
    | "#minecraft:trades/desert_common"
    | "#minecraft:trades/jungle_common"
    | "#minecraft:trades/plains_common"
    | "#minecraft:trades/savanna_common"
    | "#minecraft:trades/snow_common"
    | "#minecraft:trades/swamp_common"
    | "#minecraft:trades/taiga_common";

export type VanillaLocationBasedEffectTypes = (string & {}) | "minecraft:attribute";