import net, { Socket } from "node:net";
import { error, info } from "../Debug";
import HTTPRequest from "./HTTPRequest";

// @ts-ignore
import { EventEmitter } from "node:stream";
import HTTPResponse, { MIMETypes } from "./HTTPResponse";
import HTTPFrame from "./HTTPFrame";
import Web from "./WebDistribution";
import path from "node:path";

type WebServerOptions = {
    mime: {
        default: MIMETypes | (string & {});
        associations: Record<`.${string}`, MIMETypes | (string & {})>
    }
};

interface WebServerEvents {
    "route": [ string, HTTPRequest, Socket ];
}
export default class WebServer extends EventEmitter<WebServerEvents> {
    public static DEFAULT_ASSOCIATIONS: WebServerOptions["mime"]["associations"] = {
        ".html": "text/html",
        ".txt": "text/plain",
        ".css": "text/css",
        ".js": "application/javascript",
        ".xml": "application/xml",
        ".json": "application/json",
        ".jpg": "image/jpeg",
        ".png": "image/png",
        ".gif": "image/gif",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
        ".ico": "image/x-icon",
        ".svg": "image/svg+xml",
        ".mp4": "video/mp4",
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".pdf": "application/pdf",
        ".map": "application/json",
        ".woff": "font/woff",
        ".woff2": "font/woff2",
        ".ttf": "font/ttf",
        ".eot": "application/vnd.ms-fontobject",
        ".otf": "font/otf"
    };

    public readonly server: net.Server;

    public mimeOptions: WebServerOptions["mime"];

    private _started: boolean = false;

    constructor({ mime }: WebServerOptions = {
        mime: { default: "text/plain", associations: WebServer.DEFAULT_ASSOCIATIONS }
    }) {
        super();

        this.mimeOptions = mime;

        this.server = new net.Server();

        this.server.on("connection", socket => new HTTPFrame(this, socket));
        this.server.on("error", (err) => error(err));

        this.on("route", (route, request, socket) => {
            const ext = path.posix.extname(route);

            if (ext !== "") {
                const response = new HTTPResponse(404, "Not Found");
                response.contentType = this.mimeOptions.default;
                response.body = `${request.method} ${route}`;
                socket.end(response.payload);
            } else {
                this.sendAutogeneratedFile("/index.html", socket);
            }
        });
    }

    public start(port: number) {
        if (this._started) return;
        this._started = true;

        this.server.listen(port, () => {
            info(`Web server started on ${port}`);
        });
    }

    public sendAutogeneratedFile(filepath: string, socket: Socket) {
        const response = new HTTPResponse(200, "OK");
        if (filepath.includes(".")) {
            const ext = path.posix.extname(filepath) as `.${string}`;
            response.contentType = this.mimeOptions.associations[ext] || this.mimeOptions.default;
        } else {
            response.contentType = this.mimeOptions.default;
        }
        response.body = Web[filepath];
        socket.end(response.payload);
    }
}