import { Socket } from "node:net";
import HTTPRequest from "./HTTPRequest";

import Web from "./WebDistribution";
import path from "node:path";
import HTTPResponse from "./HTTPResponse";
import WebServer from "./WebServer";

export default class HTTPConnection {
    private _requestBuffer!: HTTPRequest;
    private _contentLength = -1;
    private _buffer: Buffer = Buffer.alloc(0);
    private _ended: boolean = false;

    constructor(
        public readonly server: WebServer,
        public readonly socket: Socket
    ) {
        this.socket.setTimeout(60 * 1000);

        socket.on("data", chunk => {
            if (this._ended) return;
            
            const data = typeof chunk === "string" ? Buffer.from(chunk) : chunk;
            this._buffer = Buffer.concat([this._buffer, data]);
            this._pump();
        });

        socket.on("error", (err) => {
            console.error(err);
            this.socket.destroy();
        });

        socket.on("close", () => this._ended = true);
        socket.on("timeout", () => this.close());
    }

    private _pump() {
        while (true) {
            if (this._contentLength === -1) {
                const headerEnd = this._buffer.indexOf("\r\n\r\n");
                if (headerEnd === -1) return;

                const headerBlock = this._buffer.subarray(0, headerEnd).toString("utf8");
                this._buffer = this._buffer.subarray(headerEnd + 4);

                const lines = headerBlock.split("\r\n");
                this._handleHeader(lines);
                continue;
            }

            if (!this._buildRequestBody()) {
                return;
            }
        }
    }
    
    private _buildRequestBody(): boolean {
        if (this._contentLength < 0) return false;

        if (this._buffer.length < this._contentLength) {
            return false;
        }

        const body = this._buffer.subarray(0, this._contentLength);
        this._buffer = this._buffer.subarray(this._contentLength);

        this._requestBuffer.body = Uint8Array.from(body);
        this._contentLength = -1;

        this._handleRequest(this._requestBuffer);
        return true;
    }

    private _handleHeader(lines: string[]) {
        if (lines.length === 0) return;

        const [method, path, protocol] = lines[0].split(" ");
        if (!method || !path || !protocol) return;

        const headers: Record<string, string> = {};

        for (const line of lines.slice(1)) {
            const index = line.indexOf(":");
            if (index !== -1) {
                const name = line.slice(0, index).trim().toLowerCase();
                const value = line.slice(index + 1).trim();
                headers[name] = value;
            }
        }

        this._requestBuffer = new HTTPRequest(path, protocol as any, method as any, headers);
        this._contentLength = this._requestBuffer.contentLength || 0;
    }

    private _handleRequest(request: HTTPRequest) {
        const route = request.route;
        const staticPaths = Object.keys(Web);
        const indexAlternate = path.posix.join(route, "index.html");
        let file: string | null = null;

        for (const filePath of staticPaths) {
            const normalizedPath = filePath.toLowerCase();

            if (normalizedPath == route.toLowerCase()) {
                file = filePath;
                break;
            }

            if (normalizedPath == indexAlternate.toLowerCase()) {
                file = filePath;
                break;
            }
        }

        if (file) {
            const response = this.server.autogeneratedFile(file);
            this.send(response);
        } else {
            this.server.emit("route", route, request, this);
        }

        const connectionStatus = request.getHeader("Connection");

        if (connectionStatus == "close") {
            this.close();
        }
    }

    public close() {
        if (this._ended || this.socket.destroyed) return;
        this._ended = true;
        this.socket.end();
    }

    public send(response: HTTPResponse) {
        if (this._ended) return;
        const payload = response.payload;
        this.socket.write(payload);
    }
}