// @ts-ignore
import { HTTPResponse, MIMETypeAssociationProvider, MIMETypes } from "@/WebPanel/HTTP";
import WebDistribution from "@generated/web-distribution.auto"
import path from "node:path";

export function autogeneratedFile(filepath: string, status: number = 200) {
    const response = new HTTPResponse(status);
    if (filepath.includes(".")) {
        const ext = path.posix.extname(filepath) as `.${string}`;
        response.contentType = MIMETypeAssociationProvider.get(ext);
    } else {
        response.contentType = MIMETypeAssociationProvider.default;
    }
    response.body = WebDistribution[filepath] ?? new Uint8Array();
    response.setHeader("Cache-Control", "max-age=" + 60 * 60 * 12);
    return response;
}

export const validPaths = Object.keys(WebDistribution);