import net, { Socket } from "node:net";
import { error, info } from "../Debug";

// @ts-ignore
import { NodeblockMonitor } from "@/Network/NodeblockServer";
import path from "node:path";
import { EventEmitter } from "node:stream";
import * as WebDistribution from "./WebDistribution";

import HTTP, { HTTPIncomingRequest, HTTPResponse } from "@/WebPanel/HTTP";
import WS from "@/WebPanel/WS";


type WebServerOptions = {}

type RouteHandler = (request: HTTPIncomingRequest, response: Response, next: () => void) => void;
export type WebConnectionHandler = (server: WebServer, socket: Socket) => void;

interface WebServerEvents {
    "route": [ HTTPIncomingRequest, Socket ];
    
    "websocketmessage": [ Socket, Uint8Array | string ];
    "websocketclose": [ Socket ];
    "websocketopen": [ Socket ];
}
export default class WebServer extends EventEmitter<WebServerEvents> {
    public readonly server: net.Server;

    private _handlers: { route: string, handler: RouteHandler }[] = [];
    private _started: boolean = false;

    constructor({}: WebServerOptions = {}) {
        super();

        this.server = new net.Server();

        this.server.on("connection", socket => HTTP(this, socket));
        this.server.on("error", (err) => error(err));

        this.on("route", (request, socket) => {
            const route = request.route;
            const indexAlternate = path.posix.join(route, "index.html");
            let file: string | null = null;

            for (const filePath of WebDistribution.validPaths) {
                const normalizedPath = filePath.toLowerCase();

                if (normalizedPath == route.toLowerCase()) {
                    file = filePath;
                    break;
                }

                if (normalizedPath == indexAlternate.toLowerCase()) {
                    file = filePath;
                    break;
                }
            }

            let response = Response.from(this, socket, file ? WebDistribution.autogeneratedFile(file) : WebDistribution.autogeneratedFile("/index.html", 404));

            if (this._handlers.length === 0) {
                response.send();
            } else {
                let pipelineIndex = -1;

                const selectivePipeline = this._handlers.filter(entry => entry.route === "" || entry.route === request.route);

                const next = () => {
                    if (response.ended) return;

                    pipelineIndex++;
                    
                    if (pipelineIndex >= selectivePipeline.length) {
                        response.send();
                        return
                    }

                    const { handler } = selectivePipeline[pipelineIndex];
                    handler(request, response, next);
                }
                
                next();
            }
        });
    }

    private _createEntry(routeOrHandler?: string | RouteHandler, handler?: RouteHandler) {
        let entry = { route: "", handler: handler! };

        if (typeof routeOrHandler === "string") {
            entry.route = routeOrHandler;
        } else {
            entry.handler = routeOrHandler!;
        }

        return entry;
    }

    public useFirst(handler: RouteHandler): this;
    public useFirst(route: string, handler: RouteHandler): this;
    public useFirst(routeOrHandler?: string | RouteHandler, handler?: RouteHandler): this {
        this._handlers.unshift(this._createEntry(routeOrHandler, handler));
        return this;
    }

    public use(handler: RouteHandler): this;
    public use(route: string, handler: RouteHandler): this;
    public use(routeOrHandler?: string | RouteHandler, handler?: RouteHandler): this {
        this._handlers.push(this._createEntry(routeOrHandler, handler));
        return this;
    }

    public start(port: number) {
        if (this._started) return;
        this._started = true;

        this.server.listen(port, () => {
            info(`Web server started on http://localhost:${port}`);
        });
    }

    public useDefaultWebPanel(): this {
        this.use("/", (req, res, next) => {
            const { connection, upgrade, "sec-websocket-key": websocketKey } = req.headers;

            if (connection.toLowerCase() == "upgrade") {
                if (!upgrade) {
                    res.status = 400;
                    res.send().close();
                    return;
                }
                const upgradeOptions = upgrade.split(",").map(s => s.trim());
    
                if (upgradeOptions.includes("websocket")) {
                    res.upgrade(WS(websocketKey));
                } else {
                    res.status = 400;
                    res.send().close();
                }
            } else {
                next();
            }
        });
        return this;
    }

    public async stop(): Promise<void> {
        return new Promise(res => this.server.close(() => res()));
    }
}

export class Response extends HTTPResponse {
    private _ended: boolean;

    constructor(
        public readonly server: WebServer,
        public readonly socket: Socket
    ) {
        super();
        this._ended = socket.destroyed || socket.closed;
        if (this._ended) {
            console.warn("Response connection already ended");
        }
    }

    public upgrade(payload: string | Uint8Array, newHandler: WebConnectionHandler): void;
    public upgrade(newHandler: WebConnectionHandler): void;
    public upgrade(newHandlerOrPayload: WebConnectionHandler | string | Uint8Array, newHandler?: WebConnectionHandler) {
        let handler: WebConnectionHandler;

        if (typeof newHandlerOrPayload === "function") {
            this._ended = true;
            handler = newHandlerOrPayload;
        } else {
            if (!this._ended) {
                this.send(newHandlerOrPayload);
            }
            handler = newHandler!;
        }
        this.socket.removeAllListeners();
        handler(this.server, this.socket);
    }
    
    public send(payload?: string | Uint8Array, close: boolean = false) {
        if (this._ended) return this;
        this._ended = true;
        if (payload) this.body = payload;
        this.socket.write(this.payload);
        if (close) this.close();
        return this;
    }

    public close() {
        this._ended = true;
        this.socket.end();
    }

    public get ended() { return this._ended; }

    public static from(server: WebServer, socket: Socket, response: Response | HTTPResponse): Response {
        const r = new Response(server, socket);
        r.body = response.body;
        r.headers = response.headers;
        r.protocol = response.protocol;
        r.status = response.status;
        r.reasonPhrase = response.reasonPhrase;
        return r;
    }
}

export class WebMonitor extends NodeblockMonitor {
    private _webserver?: WebServer;

    public attachServer(webserver: WebServer) {
        this._webserver = webserver;
    }
}