import net from "node:net";
import { error, info } from "../Debug";

// @ts-ignore
import { NodeblockMonitor } from "@/Network/NodeblockServer";
import HTTPConnection, { HTTPRequest, HTTPResponse, MIMETypes } from "@/WebPanel/HTTP";
import path from "node:path";
import { EventEmitter } from "node:stream";
import WebDistribution from "./WebDistribution";

import Web from "./WebDistribution";

type WebServerOptions = {
    mime: {
        default: MIMETypes | (string & {});
        associations: Record<`.${string}`, MIMETypes | (string & {})>
    }
};

type RouteHandler = (request: HTTPRequest, response: HTTPResponse, next: () => void) => void;

interface WebServerEvents {
    "route": [ HTTPRequest, HTTPConnection ];
}
export default class WebServer extends EventEmitter<WebServerEvents> {
    public static DEFAULT_ASSOCIATIONS: WebServerOptions["mime"]["associations"] = {
        ".html": "text/html",
        ".txt": "text/plain",
        ".css": "text/css",
        ".js": "application/javascript",
        ".xml": "application/xml",
        ".json": "application/json",
        ".jpg": "image/jpeg",
        ".png": "image/png",
        ".gif": "image/gif",
        ".jpeg": "image/jpeg",
        ".webp": "image/webp",
        ".ico": "image/x-icon",
        ".svg": "image/svg+xml",
        ".mp4": "video/mp4",
        ".mp3": "audio/mpeg",
        ".wav": "audio/wav",
        ".pdf": "application/pdf",
        ".map": "application/json",
        ".woff": "font/woff",
        ".woff2": "font/woff2",
        ".ttf": "font/ttf",
        ".eot": "application/vnd.ms-fontobject",
        ".otf": "font/otf"
    };

    public readonly server: net.Server;

    public mimeOptions: WebServerOptions["mime"];

    private _handlers: { route: string, handler: RouteHandler }[] = [];
    private _started: boolean = false;

    constructor({ mime }: WebServerOptions = {
        mime: { default: "text/plain", associations: WebServer.DEFAULT_ASSOCIATIONS }
    }) {
        super();

        this.mimeOptions = mime;

        this.server = new net.Server();

        this.server.on("connection", socket => new HTTPConnection(this, socket));
        this.server.on("error", (err) => error(err));

        this.on("route", (request, connection) => {
            const staticPaths = Object.keys(Web);
            const route = request.route;
            const indexAlternate = path.posix.join(route, "index.html");
            let file: string | null = null;

            for (const filePath of staticPaths) {
                const normalizedPath = filePath.toLowerCase();

                if (normalizedPath == route.toLowerCase()) {
                    file = filePath;
                    break;
                }

                if (normalizedPath == indexAlternate.toLowerCase()) {
                    file = filePath;
                    break;
                }
            }

            let response = file ? this.autogeneratedFile(file) : this.autogeneratedFile("/index.html", 404);

            if (this._handlers.length === 0) {
                connection.send(response);
            } else {
                let pipelineIndex = -1;

                const selectivePipeline = this._handlers.filter(entry => entry.route === "" || entry.route === request.route);

                const next = () => {
                    if (connection.ended) return;
                    if (pipelineIndex >= selectivePipeline.length) {
                        connection.send(response);
                        return
                    }
                    pipelineIndex++;

                    const { handler } = selectivePipeline[pipelineIndex];
                    handler(request, response, next);
                }
                next();
            }
        });
    }

    private _createEntry(routeOrHandler?: string | RouteHandler, handler?: RouteHandler) {
        let entry = { route: "", handler: handler! };

        if (typeof routeOrHandler === "string") {
            entry.route = routeOrHandler;
        } else {
            entry.handler = routeOrHandler!;
        }

        return entry;
    }

    public useFirst(handler: RouteHandler): this;
    public useFirst(route: string, handler: RouteHandler): this;
    public useFirst(routeOrHandler?: string | RouteHandler, handler?: RouteHandler): this {
        this._handlers.unshift(this._createEntry(routeOrHandler, handler));
        return this;
    }

    public use(handler: RouteHandler): this;
    public use(route: string, handler: RouteHandler): this;
    public use(routeOrHandler?: string | RouteHandler, handler?: RouteHandler): this {
        this._handlers.push(this._createEntry(routeOrHandler, handler));
        return this;
    }

    public start(port: number) {
        if (this._started) return;
        this._started = true;

        this.server.listen(port, () => {
            info(`Web server started on http://localhost:${port}`);
        });
    }

    public autogeneratedFile(filepath: string, status: number = 200) {
        const response = new HTTPResponse(status);
        if (filepath.includes(".")) {
            const ext = path.posix.extname(filepath) as `.${string}`;
            response.contentType = this.mimeOptions.associations[ext] || this.mimeOptions.default;
        } else {
            response.contentType = this.mimeOptions.default;
        }
        response.body = WebDistribution[filepath] ?? new Uint8Array();
        response.setHeader("Cache-Control", "max-age=" + 60 * 60 * 12);
        return response;
    }
}

export class WebMonitor extends NodeblockMonitor {
    private _webserver?: WebServer;

    public attachServer(webserver: WebServer) {
        this._webserver = webserver;
    }
}